language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev --prefer-dist --no-interaction

script: bin/phpunit --exclude-group end2end --coverage-clover=coverage.clover --coverage-text

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
